
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CREATE INT NONE OBJECT PERIOD STRING_LITERAL\n    exp : crt\n           \n    \n   crt : CREATE OBJECT \n       | CREATE OBJECT float float float\n       | CREATE OBJECT float float float INT\n   \n   float : INT PERIOD INT\n         | INT\n   \n    list : term\n        | list COMMA term\n    \n    term : INT\n        | STRING_LITERAL\n        \n    '
    
_lr_action_items = {'CREATE':([0,],[3,]),'$end':([1,2,4,6,9,10,11,],[0,-1,-2,-6,-3,-5,-4,]),'OBJECT':([3,],[4,]),'INT':([4,5,6,7,8,9,10,],[6,6,-6,6,10,11,-5,]),'PERIOD':([6,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'crt':([0,],[2,]),'float':([4,5,7,],[5,7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> crt','exp',1,'p_exp','map_parser.py',14),
  ('crt -> CREATE OBJECT','crt',2,'p_crt','map_parser.py',21),
  ('crt -> CREATE OBJECT float float float','crt',5,'p_crt','map_parser.py',22),
  ('crt -> CREATE OBJECT float float float INT','crt',6,'p_crt','map_parser.py',23),
  ('float -> INT PERIOD INT','float',3,'p_float','map_parser.py',78),
  ('float -> INT','float',1,'p_float','map_parser.py',79),
  ('list -> term','list',1,'p_list','map_parser.py',90),
  ('list -> list COMMA term','list',3,'p_list','map_parser.py',91),
  ('term -> INT','term',1,'p_term','map_parser.py',101),
  ('term -> STRING_LITERAL','term',1,'p_term','map_parser.py',102),
]
